# Generated by Django 2.2.7 on 2020-02-03 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mcq', '0002_auto_20180727_2247'),
    ]

    operations = [
        migrations.AddField(
            model_name='mcqquestion',
            name='fill',
            field=models.BooleanField(default=False),
        ),
    ]
