# Generated by Django 2.2.7 on 2020-02-03 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0005_auto_20200203_1551'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='quiz',
            options={'verbose_name': 'Quiz', 'verbose_name_plural': 'Quizes'},
        ),
        migrations.AddField(
            model_name='progress',
            name='credit',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
