# Generated by Django 2.2.7 on 2020-02-03 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0006_auto_20200204_0255'),
    ]

    operations = [
        migrations.AlterField(
            model_name='progress',
            name='credit',
            field=models.IntegerField(default=0),
        ),
    ]
