# Generated by Django 2.2.7 on 2020-02-03 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fillintheblanks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fillquestion',
            name='answer_order',
            field=models.CharField(blank=True, choices=[('content', 'Content'), ('none', 'None')], help_text='The order in which multichoice                     answer options are displayed                     to the user', max_length=30, null=True, verbose_name='Answer Order'),
        ),
    ]
