# Generated by Django 2.2.7 on 2020-02-03 13:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fillintheblanks', '0002_fillquestion_answer_order'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fillanswer',
            old_name='answer',
            new_name='content',
        ),
    ]
